wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1655353800
    t:
      1:
      - 1
      - 3
      - 5
      - 41
      - 53
      - 55
      4: 3.7.10
      5: 0.12.16
      8:
      - 1
      - 5
